import { useRef, useState } from 'react'
import { Camera, ChevronDown, Code, Plus, Scan, Sparkles, Trash2 } from 'lucide-react'
import { SmartPromptEditor, type SmartInsertOption, type SmartPromptEditorHandle } from './SmartPromptEditor'
import { compileScene } from '../lib/h3SceneCompiler'
import { applySceneCommand, applySceneSuggestions, cameraAttributes, cameraOptions, defaultPreservedAttributes, extractSceneDialogue, parseStyleValues, preserveAttributes, resizeScene, suggestScene, value, type Attribute, type Camera as CameraState, type ScenePromptState, type SceneReference } from '../lib/scenePromptState'
import '../scene-composer.css'
import { SceneIssues } from './SceneIssues'

function preserveSummary(ref: SceneReference) {
  if (ref.preserve.length) return `Preserving: ${ref.preserve.map(item => item[0].toUpperCase() + item.slice(1)).join(' · ')}`
  if (ref.file.referenceRole === 'wardrobe') return 'Wardrobe reference · enable Preserve to retain the outfit'
  return ref.anchor ? `${ref.anchor} frame` : ref.audio?.layer || ref.videoRole || 'Choose a role'
}

export function SceneComposer({ state, onChange, options, onAddReference, onManageReferences, onAnalyzeReference }: { state: ScenePromptState; onChange(state: ScenePromptState): void; options: SmartInsertOption[]; onAddReference(): void; onManageReferences(): void; onAnalyzeReference?(path: string): Promise<Partial<Record<Attribute, string>>> }) {
  const editor = useRef<SmartPromptEditorHandle>(null)
  const [activeShot, setActiveShot] = useState(0)
  const [command, setCommand] = useState('')
  const [commandOpen, setCommandOpen] = useState(false)
  const [analysis, setAnalysis] = useState<{ id: string; fields: Partial<Record<Attribute, string>> } | null>(null)
  const [analyzing, setAnalyzing] = useState('')
  const [analysisError, setAnalysisError] = useState('')
  const [referencesOpen, setReferencesOpen] = useState(true)
  const [shotsOpen, setShotsOpen] = useState(true)
  const compiled = compileScene(state)
  const suggestions = suggestScene(state.scene)
  const shotIndex = Math.min(activeShot, state.shots.length - 1)
  const shot = state.shots[shotIndex]
  const camera = shotIndex === 0 ? state.camera : shot?.camera || {}
  const setCamera = (key: keyof CameraState, text: string) => onChange(shotIndex === 0 ? { ...state, camera: { ...state.camera, [key]: value(text) } } : { ...state, shots: state.shots.map((item, index) => index === shotIndex ? { ...item, camera: { ...item.camera, [key]: value(text) } } : item) })
  const updateRef = (id: string, update: Partial<SceneReference>) => onChange({ ...state, references: state.references.map(ref => ref.id === id ? { ...ref, ...update } : ref) })
  const setView = (view: ScenePromptState['view']) => onChange({ ...state, view, manualPrompt: view === 'manual' && !state.manualPrompt ? compiled.prompt : state.manualPrompt })
  const executeCommand = () => {
    const match = command.match(/^\/?\/?(\w+)\s+(.+)$/)
    if (match) { onChange(applySceneCommand(state, match[1], match[2])); setCommand(''); setCommandOpen(false) }
  }
  const characterSource = (characterId: string, attribute: Attribute) => {
    const numbers = state.references
      .filter(ref => ref.ownerId === characterId && ref.preserve.includes(attribute))
      .map(ref => Number(compiled.references.find(item => item.id === ref.id)?.label.match(/\d+/)?.[0]))
      .filter(Number.isFinite)
      .sort((a, b) => a - b)
    if (!numbers.length) return 'Character Default'
    if (numbers.length > 1 && numbers.every((number, index) => index === 0 || number === numbers[index - 1] + 1)) return `Pictures ${numbers[0]}–${numbers.at(-1)}`
    return `${numbers.length === 1 ? 'Picture' : 'Pictures'} ${numbers.join(', ')}`
  }
  return <section className="scene-composer" aria-label="Scene Composer">
    <nav className="scene-view-tabs" aria-label="Scene view">{(['creative', 'compiled', 'manual'] as const).map(view => <button key={view} type="button" aria-pressed={state.view === view} className={state.view === view ? 'selected' : ''} onClick={() => setView(view)}>{view === 'creative' ? <Camera size={15} /> : <Code size={15} />}{view === 'creative' ? 'Scene Composer' : view === 'compiled' ? 'Compiled H3 View' : 'Manual Override'}</button>)}<button type="button" onClick={() => (document.querySelector('[data-inspector-tab="render"]') as HTMLButtonElement | null)?.click()}>Render Settings</button><button type="button" onClick={() => (document.querySelector('[data-inspector-tab="preview"]') as HTMLButtonElement | null)?.click()}>Preview</button></nav>
    {state.view === 'creative' ? <>
      <div className="scene-authoring"><div><div className="scene-heading"><strong>1. Scene</strong><small>Describe what happens in this shot.</small></div>
        <SmartPromptEditor ref={editor} id="scene-description" value={state.scene} onChange={scene => onChange({ ...state, scene })} ariaLabel="Scene" rows={6} placeholder="Same woman, same clothes, same kitchen. An extreme close-up as she notices something above the camera…" options={options} onCommand={(item, scene) => { const next = applySceneCommand({ ...state, scene }, item.category, item.label, item.insertion); onChange(next) }} />
        <div className="scene-command-row">{['camera', 'shot', 'character', 'sound', 'style', 'preserve'].map(category => <button key={category} type="button" onClick={() => { setCommand(`//${category} `); setCommandOpen(true) }}>//{category}</button>)}<button type="button" title="Browse production commands" onClick={() => editor.current?.open()}><Sparkles size={14} /></button></div>
        {commandOpen && <form className="scene-command-input" onSubmit={event => { event.preventDefault(); executeCommand() }}><input autoFocus id="scene-command" aria-label="Scene command" placeholder="//shot Extreme Close-Up" value={command} onChange={event => setCommand(event.target.value)} /><button type="submit" disabled={!/^\/?\/?\w+\s+\S/.test(command)}>Apply</button></form>}
      </div><aside className="scene-suggestions"><strong>Scene suggestions</strong>{suggestions.length ? suggestions.map((item, index) => <span key={`${item.field}-${index}`} title={`Detected from: ${item.evidence}`}><Scan size={13} />{item.value}<em>AI</em></span>) : <p>Camera suggestions appear as you describe the scene.</p>}<button type="button" disabled={!suggestions.length} onClick={() => onChange(applySceneSuggestions(state))}>Apply suggestions</button><small>Explicit choices and locks stay in place.</small></aside></div>
      <div className="scene-section scene-major-panel"><div className="scene-heading"><strong>2. References ({state.references.length})</strong><button type="button" onClick={onManageReferences}>Character library & media</button><button type="button" className="panel-collapse" aria-expanded={referencesOpen} onClick={() => setReferencesOpen(!referencesOpen)}><ChevronDown size={14} className={referencesOpen ? 'rotated' : ''} />{referencesOpen ? 'Collapse' : 'Expand'}</button></div>
        {referencesOpen && <div className="scene-reference-grid">{state.references.map(ref => <article key={ref.id} data-reference-id={ref.id} className={`scene-reference-card ${ref.anchor ? 'anchored' : ''}`}>
          <div className="scene-reference-image">{ref.file.preview && ref.file.kind === 'image' ? <img src={ref.file.preview} alt={ref.name} /> : <span>{ref.file.kind.toUpperCase()}</span>}<b>{compiled.references.find(item => item.id === ref.id)?.label.replace(/[<>]/g, '')}</b>{ref.anchor === 'opening' && <em className="opening-frame-badge">0.00s OPENING FRAME</em>}</div><div className="scene-reference-body"><div className="reference-role-badges">{(ref.preserve.length ? ref.preserve : [ref.audio?.layer || ref.videoRole || 'reference']).slice(0, 3).map(role => <span key={role}>{String(role).toUpperCase()}</span>)}</div><strong title={ref.name}>{ref.name}</strong>
          {ref.file.kind === 'image' && <div className="scene-reference-toggles"><label><input type="checkbox" checked={ref.anchor === 'opening'} onChange={event => updateRef(ref.id, { anchor: event.target.checked ? 'opening' : undefined, reviewed: false })} />Opening Frame</label><label title={ref.file.referenceRole === 'wardrobe' ? 'Keep this approved outfit on the character throughout the shot.' : 'Preserve the selected visual attributes while allowing a new composition.'}><input type="checkbox" aria-label={`Preserve ${ref.name}`} checked={!!ref.preserve.length} onChange={event => updateRef(ref.id, { preserve: event.target.checked ? defaultPreservedAttributes(ref) : [] })} />Preserve</label></div>}
          <small className={`scene-retained ${ref.file.referenceRole === 'wardrobe' && !ref.preserve.length ? 'scene-retained-warning' : ''}`}>{preserveSummary(ref)}</small>
          {ref.file.kind === 'image' && onAnalyzeReference && <button type="button" disabled={!!analyzing} onClick={async () => { setAnalyzing(ref.id); setAnalysisError(''); try { setAnalysis({ id: ref.id, fields: await onAnalyzeReference(ref.file.path) }) } catch (error) { setAnalysisError(error instanceof Error ? error.message : String(error)) } finally { setAnalyzing('') } }}>{analyzing === ref.id ? 'Analyzing…' : 'Analyze visual details'}</button>}
          {analysis?.id === ref.id && <div className="scene-analysis-review"><strong>Suggested observations <em>AI</em></strong>{Object.entries(analysis.fields).filter(([,text]) => text).map(([field,text]) => <p key={field}><b>{field}</b>: {text}</p>)}<button type="button" onClick={() => { updateRef(ref.id, { observed: { ...analysis.fields, ...Object.fromEntries(Object.entries(ref.observed).filter(([, text]) => !!text)) }, reviewed: false }); setAnalysis(null) }}>Apply observations</button><button type="button" onClick={() => setAnalysis(null)}>Dismiss</button><small>Your existing observations stay in place. Framing is observed separately from preservation.</small></div>}
          {ref.file.kind === 'video' && <label><input type="checkbox" checked={!!ref.embeddedAudio} onChange={event => updateRef(ref.id, { embeddedAudio: event.target.checked ? { relation: 'reference', layer: 'ambience', description: 'The video’s ambient sound texture; do not inherit speech or music.' } : undefined })} />Use video audio</label>}
          <details><summary>Retained attributes & ownership <ChevronDown size={12} /></summary><label>Character owner<select value={ref.ownerId || ''} onChange={event => updateRef(ref.id, { ownerId: event.target.value || undefined })}><option value="">Scene / no character</option>{state.characters.map(character => <option key={character.id} value={character.id}>{character.name}</option>)}</select></label>
          {ref.file.kind !== 'audio' && <><div className="scene-attribute-grid">{preserveAttributes.map(attribute => <label key={attribute}><input type="checkbox" checked={ref.preserve.includes(attribute)} onChange={event => updateRef(ref.id, { preserve: event.target.checked ? [...ref.preserve, attribute] : ref.preserve.filter(item => item !== attribute) })} />{attribute}</label>)}</div><p>Framing, shot size, pose and angle are excluded unless locked below.</p><div className="scene-attribute-grid">{cameraAttributes.map(attribute => <label key={attribute}><input type="checkbox" checked={ref.locks.includes(attribute)} onChange={event => updateRef(ref.id, { locks: event.target.checked ? [...ref.locks, attribute] : ref.locks.filter(item => item !== attribute) })} />Lock {attribute}</label>)}</div>
          {ref.preserve.map(attribute => <label key={attribute}>{attribute} observed <em>PRESERVE</em><input value={ref.observed[attribute] || ''} placeholder="Describe the relevant visual details" onChange={event => updateRef(ref.id, { observed: { ...ref.observed, [attribute]: event.target.value } })} /></label>)}
          {ref.file.kind === 'image' && <><label>Frame role<select value={ref.anchor || ''} onChange={event => updateRef(ref.id, { anchor: event.target.value as SceneReference['anchor'] || undefined, reviewed: false })}><option value="">Reusable reference</option><option value="opening">Literal opening frame</option><option value="ending">Literal ending frame</option></select></label>{ref.anchor && <>{(['shotSize', 'angle'] as const).map(attribute => <label key={attribute}>Frame {attribute}<select value={ref.observed[attribute] || ''} onChange={event => updateRef(ref.id, { observed: { ...ref.observed, [attribute]: event.target.value }, reviewed: false })}><option value="">Unknown — review visually</option>{cameraOptions[attribute].map(option => <option key={option}>{option}</option>)}</select></label>)}<label><input type="checkbox" checked={!!ref.reviewed} onChange={event => updateRef(ref.id, { reviewed: event.target.checked })} />I reviewed the frame against this shot's direction</label><small>Literal anchors retain the full visual state at their assigned time.</small></>}</>}
          {ref.file.kind === 'video' && <label>Video relationship<select value={ref.videoRole} onChange={event => updateRef(ref.id, { videoRole: event.target.value as SceneReference['videoRole'] })}>{['motion', 'structure', 'continuation', 'editing'].map(role => <option key={role}>{role}</option>)}</select></label>}</>}
          {ref.audio && <><label>Audio relationship<select value={ref.audio.relation} onChange={event => updateRef(ref.id, { audio: { ...ref.audio!, relation: event.target.value as NonNullable<SceneReference['audio']>['relation'] } })}>{['reference', 'fully_copy', 'partially_copy', 'weak_reference'].map(role => <option key={role}>{role}</option>)}</select></label><label>Audible layer<select value={ref.audio.layer} onChange={event => updateRef(ref.id, { audio: { ...ref.audio!, layer: event.target.value as NonNullable<SceneReference['audio']>['layer'] } })}>{['voice', 'ambience', 'music', 'soundtrack'].map(role => <option key={role}>{role}</option>)}</select></label><label>Speaker<select value={ref.audio.speakerId || ''} onChange={event => updateRef(ref.id, { audio: { ...ref.audio!, speakerId: event.target.value } })}><option value="">Choose for voice reference</option>{state.characters.map(character => <option key={character.id} value={character.id}>{character.name}</option>)}</select></label><label>Sound characteristics or copied layer<input value={ref.audio.description} onChange={event => updateRef(ref.id, { audio: { ...ref.audio!, description: event.target.value } })} /></label></>}
          </details></div></article>)}<button type="button" className="scene-add-reference" onClick={onAddReference}><Plus size={25} />Add Reference<small>Image · Video · Audio</small></button></div>}
      </div>
      <div className="scene-section scene-major-panel"><div className="scene-heading"><strong>3. Shot Builder</strong><span>{shot?.start.toFixed(2)} — {shot?.end.toFixed(2)}s</span><label>Clip duration<input aria-label="Clip duration" type="number" min="1" max="15" step="0.5" value={state.duration} onChange={event => onChange(resizeScene(state, +event.target.value))} /></label><button type="button" className="panel-collapse" aria-expanded={shotsOpen} onClick={() => setShotsOpen(!shotsOpen)}><ChevronDown size={14} className={shotsOpen ? 'rotated' : ''} />{shotsOpen ? 'Collapse' : 'Expand'}</button></div>{shotsOpen && <><div className="scene-shot-tabs">{state.shots.map((item, index) => <button type="button" key={item.id} className={index === shotIndex ? 'selected' : ''} onClick={() => setActiveShot(index)}>Shot {index + 1}</button>)}<button type="button" disabled={!shot || shot.end - shot.start < 1} onClick={() => { const last = state.shots.at(-1)!; const split = Math.round((last.start + last.end) / 2 * 1000) / 1000; onChange({ ...state, shots: [...state.shots.slice(0, -1), { ...last, end: split }, { id: `shot-${Date.now()}`, start: split, end: last.end, description: '', camera: {}, characterIds: [] }] }); setActiveShot(state.shots.length) }}><Plus size={13} />Add Shot</button>{state.shots.length > 1 && <button type="button" onClick={() => { const remaining = state.shots.filter((_, index) => index !== shotIndex); const next = remaining.map((item, index) => ({ ...item, start: index * state.duration / remaining.length, end: (index + 1) * state.duration / remaining.length })); onChange({ ...state, shots: next, dialogue: state.dialogue.filter(line => line.shotId !== shot.id) }); setActiveShot(0) }}><Trash2 size={13} />Remove</button>}</div>
      <div className="scene-camera-grid">{Object.entries(cameraOptions).map(([key, choices]) => <label key={key}>{({ shotSize: 'Shot Size', angle: 'Camera Angle', movement: 'Camera Movement', speed: 'Speed', stabilization: 'Stabilization', amplitude: 'Movement Amount' } as Record<string, string>)[key]} <em>{camera[key as keyof CameraState]?.source || 'DEFAULT'}</em><select value={camera[key as keyof CameraState]?.value || ''} onChange={event => setCamera(key as keyof CameraState, event.target.value)}><option value="">From scene</option>{choices.map(choice => <option key={choice}>{choice}</option>)}{camera[key as keyof CameraState]?.value && !choices.includes(camera[key as keyof CameraState]!.value) && <option>{camera[key as keyof CameraState]!.value}</option>}</select></label>)}</div>
      {shot && <div className="scene-shot-detail"><input aria-label="Shot action" value={shot.description} placeholder="Additional action for this shot…" onChange={event => onChange({ ...state, shots: state.shots.map((item, index) => index === shotIndex ? { ...item, description: event.target.value } : item) })} /><label>End (s)<input type="number" min={shot.start + .01} max={state.duration} step="0.1" value={shot.end} onChange={event => onChange({ ...state, shots: state.shots.map((item, index) => index === shotIndex ? { ...item, end: +event.target.value } : index === shotIndex + 1 ? { ...item, start: +event.target.value } : item) })} /></label></div>}
      </>}
      </div>
      <div className="scene-lower-grid"><details className="scene-section" open><summary>4. Characters</summary>
        {state.characters.map(character => <div className="scene-character" key={character.id}>
          <div className="scene-character-portrait">{state.references.filter(ref => ref.ownerId === character.id && ref.file.preview && ref.preserve.some(attribute => ['identity', 'face', 'body'].includes(attribute))).slice(0, 3).map(ref => <img key={ref.id} src={ref.file.preview} alt={`${character.name} identity reference`} />)}<strong>{character.name}</strong></div>
          <div className="character-source-rows">{(['identity', 'wardrobe', 'hair'] as Attribute[]).map(attribute => { const source = characterSource(character.id, attribute); return <div key={attribute}><span>{attribute[0].toUpperCase() + attribute.slice(1)}</span><strong>{character.attributes[attribute]?.value || source}</strong><em>{character.attributes[attribute]?.value ? character.attributes[attribute]?.source || 'USER' : source === 'Character Default' ? 'CHARACTER' : 'PRESERVE'}</em></div> })}</div>
          <details><summary>Assembly & canonical sources</summary>{(['identity', 'face', 'body', 'hair', 'wardrobe', 'accessories'] as Attribute[]).map(attribute => <label key={attribute}>{attribute} <em>{character.attributes[attribute]?.source || 'CHARACTER'}</em><input value={character.attributes[attribute]?.value || ''} placeholder="Explicit direction overrides Preserve" onChange={event => onChange({ ...state, characters: state.characters.map(item => item.id === character.id ? { ...item, attributes: { ...item.attributes, [attribute]: value(event.target.value) } } : item) })} /><select aria-label={`${character.name} ${attribute} source`} value={character.attributes[attribute]?.referenceIds?.[0] || ''} onChange={event => onChange({ ...state, references: state.references.map(ref => ref.ownerId === character.id ? { ...ref, preserve: ref.id === event.target.value ? [...new Set([...ref.preserve, attribute])] : ref.preserve.filter(item => item !== attribute) } : ref), characters: state.characters.map(item => item.id === character.id ? { ...item, attributes: { ...item.attributes, [attribute]: { ...value('', 'CHARACTER'), referenceIds: event.target.value ? [event.target.value] : [] } } } : item) })}><option value="">Assigned reference set</option>{state.references.filter(ref => ref.ownerId === character.id).map(ref => <option key={ref.id} value={ref.id}>{compiled.references.find(item => item.id === ref.id)?.label} · {ref.name}</option>)}</select></label>)}</details>
        </div>)}
        <button type="button" onClick={() => onChange({ ...state, characters: [...state.characters, { id: `character-${Date.now()}`, name: `Character ${state.characters.length + 1}`, attributes: {} }] })}>+ Add character</button>{state.characters.map(character => <input key={character.id} aria-label="Character name" value={character.name} onChange={event => onChange({ ...state, characters: state.characters.map(item => item.id === character.id ? { ...item, name: event.target.value } : item) })} />)}
      </details>
      <details className="scene-section" open><summary>5. Dialogue</summary>{state.dialogue.map(line => <div className="scene-dialogue" key={line.id}><select aria-label="Dialogue speaker" value={line.speakerIds[0] || ''} onChange={event => onChange({ ...state, dialogue: state.dialogue.map(item => item.id === line.id ? { ...item, speakerIds: [event.target.value] } : item) })}><option value="">Speaker</option>{state.characters.map(character => <option key={character.id} value={character.id}>{character.name}</option>)}</select>{(['language', 'delivery', 'text'] as const).map(field => <input key={field} aria-label={`Dialogue ${field}`} placeholder={field} value={line[field]} onChange={event => onChange({ ...state, dialogue: state.dialogue.map(item => item.id === line.id ? { ...item, [field]: event.target.value } : item) })} />)}<details><summary>Timing & delivery</summary><label>Shot<select value={line.shotId} onChange={event => onChange({ ...state, dialogue: state.dialogue.map(item => item.id === line.id ? { ...item, shotId: event.target.value, at: state.shots.find(shot => shot.id === event.target.value)!.start } : item) })}>{state.shots.map((shot, index) => <option key={shot.id} value={shot.id}>Shot {index + 1}</option>)}</select></label><label>Start (seconds)<input type="number" step="0.1" value={line.at} onChange={event => onChange({ ...state, dialogue: state.dialogue.map(item => item.id === line.id ? { ...item, at: +event.target.value } : item) })} /></label><label><input type="checkbox" checked={!!line.voiceover} onChange={event => onChange({ ...state, dialogue: state.dialogue.map(item => item.id === line.id ? { ...item, voiceover: event.target.checked } : item) })} />Off-screen voiceover</label><label>Across cuts<select value={line.continues || ''} onChange={event => onChange({ ...state, dialogue: state.dialogue.map(item => item.id === line.id ? { ...item, continues: event.target.value as typeof line.continues || undefined } : item) })}><option value="">Complete line</option><option value="to">Continues into next shot</option><option value="from">Continued from previous</option><option value="both">Both</option></select></label><label><input type="checkbox" checked={!!line.cutoff} onChange={event => onChange({ ...state, dialogue: state.dialogue.map(item => item.id === line.id ? { ...item, cutoff: event.target.checked } : item) })} />Cut off at clip end</label></details><button type="button" onClick={() => onChange({ ...state, dialogue: state.dialogue.filter(item => item.id !== line.id) })}>Remove line</button></div>)}<button type="button" disabled={!state.characters.length || !shot} onClick={() => onChange({ ...state, noDialogue: false, dialogue: [...state.dialogue, { id: `line-${Date.now()}`, shotId: shot.id, at: shot.start, speakerIds: [state.characters[0].id], language: 'English', text: '', delivery: '' }] })}>+ Add line</button></details>
      <details className="scene-section" open><summary>6. Sound & music</summary><label>Ambience & physical effects <em>{state.soundscape.source}</em><textarea rows={3} value={state.soundscape.value} onChange={event => onChange({ ...state, soundscape: value(event.target.value) })} /></label><label>Audience-only music <em>{state.music.source}</em><textarea rows={2} placeholder="No score unless requested" value={state.music.value} onChange={event => onChange({ ...state, music: value(event.target.value) })} /></label></details>
      <details className="scene-section" open><summary>7. Environment & style</summary><label>Environment <em>{state.environment.source}</em><input value={state.environment.value} onChange={event => onChange({ ...state, environment: value(event.target.value) })} /></label><label>Lighting <em>{state.lighting.source}</em><input value={state.lighting.value} onChange={event => onChange({ ...state, lighting: value(event.target.value) })} /></label><label>Style chips<input placeholder="Found footage, Low-light, Realistic" value={state.styles.map(item => item.value).join(', ')} onChange={event => onChange({ ...state, styles: parseStyleValues(event.target.value) })} /></label></details></div>
      <details className="scene-section scene-continuity-panel"><summary>Continuity & locks</summary><div className="scene-continuity-options">{(['scene', 'camera', 'exactFrame'] as const).map(key => <label key={key}><input type="checkbox" checked={state.continuity[key]} onChange={event => onChange({ ...state, continuity: { ...state.continuity, [key]: event.target.checked } })} />{key === 'scene' ? 'Keep scene continuity' : key === 'camera' ? 'Keep camera axis & screen direction' : 'Continue exact previous frame'}</label>)}</div><input aria-label="Continuity notes" value={state.continuity.notes.value} onChange={event => onChange({ ...state, continuity: { ...state.continuity, notes: value(event.target.value) } })} placeholder="Project continuity notes" /><p>Scene continuity preserves the world. Camera continuity preserves screen direction. An opening frame locks the literal visual state at 0.00s.</p></details>
    </> : <div className="scene-section"><strong>{state.view === 'manual' ? 'Manual Override — edits are saved independently' : 'Deterministic H3 output'}</strong><p>{state.view === 'manual' ? 'Automatic recompilation will not replace this text. Reference and timing checks still run.' : 'This is the exact compiler output used for rendering.'}</p><textarea className="scene-compiled" aria-label={state.view === 'manual' ? 'Manual H3 prompt' : 'Compiled H3 prompt'} readOnly={state.view !== 'manual'} value={state.view === 'manual' ? state.manualPrompt : compiled.prompt} onChange={event => onChange({ ...state, manualPrompt: event.target.value })} /></div>}
    <div className="scene-status" role="status"><strong>{compiled.mode} · {compiled.subjects.length} subjects · {state.shots.length} shots · {state.duration}s</strong><span>Compiled scene summary</span></div>
    <SceneIssues conflicts={compiled.conflicts} state={state} onChange={onChange} onReferences={onManageReferences} />
    {analysisError && <p role="alert">{analysisError}</p>}
    {extractSceneDialogue(state).dialogue.length > state.dialogue.length && <button type="button" onClick={() => onChange(extractSceneDialogue(state))}>Review detected dialogue in structured controls</button>}
    <details className="scene-section scene-debug"><summary>H3 Debug / Advanced inspector</summary><pre>{JSON.stringify({ mode: compiled.mode, subjects: compiled.subjects, references: compiled.references, timing: compiled.timing, speakerIDs: compiled.speakers, conflicts: compiled.conflicts }, null, 2)}</pre><textarea aria-label="Final compiled prompt" readOnly value={compiled.prompt} /></details>
  </section>
}
